# version: '3.3'
# services:

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

#   db:
#     image: postgres:13.0-alpine
#     ports:
#       - '5432:5432'

#     volumes:
#       - /var/lib/postgresql/data/
#     env_file: 
#       - ./.env
      
version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    restart: always

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
    restart: always

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend